name: Pre-commit CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: Check pre-commit
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install pre-commit
      uses: pre-commit/action@v3.0.1
      continue-on-error: true

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Pre-commit fixes
        commit_options: '--no-verify'
